workflows:
  upload_prebuilt_ipa:
    name: Upload Prebuilt IPA to TestFlight
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        APP_IDENTIFIER: co.median.ios.djyjab
    scripts:
      - name: Install Apple Transporter
        script: |
          curl -s 'https://storage.googleapis.com/xcodeapps/apple_notarization_tools.zip' -o apple_notarization_tools.zip
          unzip -q apple_notarization_tools.zip
          
      - name: Upload IPA to TestFlight
        script: |
          # Copy IPA to expected location
          cp fastlane/App.ipa .
          
          # Use xcrun with altool to upload
          xcrun altool --upload-app -f App.ipa \
            --apiKey $API_KEY_ID \
            --apiIssuer $API_ISSUER_ID \
            --type ios
    artifacts:
      - fastlane/App.ipa
secrets:
  - API_KEY_ID      # Your App Store Connect API Key ID (2UMQG6769T)
  - API_ISSUER_ID   # Your App Store Connect API Issuer ID
  - API_KEY_CONTENT # Your private key content