workflows:
  upload_prebuilt_ipa:
    name: Upload Prebuilt IPA to TestFlight
    max_build_duration: 60
    environment:
      vars:
        APP_IDENTIFIER: co.median.ios.djyjab
      node: none
      ruby: none
      cocoapods: false
    scripts:
      - name: Skip build (we already have the IPA)
        script: echo "Using prebuilt IPA, no Xcode build needed"
    artifacts:
      - fastlane/App.ipa
    code_signing:
      app_store_connect_api_key:
        key_id: 2UMQG6769T
        issuer_id: eff8f8f4-ea88-4b9f-a226-d1db218abb59 
        key_file: fastlane/AuthKey_2UMQG6769T.p8
    publishing:
      testflight:
        ipa_path: fastlane/App.ipa
