workflows:
  upload_prebuilt_ipa:
    name: Upload Prebuilt IPA to TestFlight
    max_build_duration: 60
    environment:
      vars:
        APP_IDENTIFIER: co.median.ios.djyjab
    scripts:
      - name: Skip build (we already have the IPA)
        script: echo "Using prebuilt IPA, no Xcode build needed"
    artifacts:
      - fastlane/App.ipa
    publishing:
      app_store_connect:
        api_key: $ASC_API_P8_KEY # Reference to the secret variable from Codemagic UI
        key_id: 2UMQG6769T
        issuer_id: eff8f8f4-ea88-4b9f-a226-d1db218abb59
        method: api
        ipa_path: fastlane/App.ipa

# The secrets block below is optional if ASC_API_P8_KEY is a global secret
# If ASC_API_P8_KEY is part of a group, you'd reference the group here.
# If it's a standalone secret, this tells Codemagic to make it available.
secrets:
  - ASC_API_P8_KEY # This just lists the name of the secret variable from UI