workflows:
  upload_prebuilt_ipa:
    name: Upload Prebuilt IPA to TestFlight
    max_build_duration: 60
    environment:
      vars:
        APP_IDENTIFIER: co.median.ios.djyjab
    scripts:
      - name: Skip build (we already have the IPA)
        script: echo "Using prebuilt IPA, no Xcode build needed"
    artifacts:
      - fastlane/App.ipa # Codemagic will look for the IPA here for publishing
    publishing:
      app_store_connect:
        private_key: $ASC_API_P8_KEY_NEW
        key_id: 2UMQG6769T
        issuer_id: eff8f8f4-ea88-4b9f-a226-d1db218abb59
        # ipa_path has been removed

secrets:
  - ASC_API_P8_KEY_NEW