workflows:
  upload_prebuilt_ipa:
    name: Upload Prebuilt IPA to TestFlight
    max_build_duration: 60
    instance_type: mac_mini_m2  # macOS is better for iOS uploads
    environment:
      vars:
        APP_IDENTIFIER: co.median.ios.djyjab
    scripts:
      - name: Upload IPA to TestFlight
        script: |
          # Install fastlane if not available
          gem install fastlane
          
          # Create minimal Fastfile in current directory
          cat > Fastfile << 'EOL'
          default_platform(:ios)
          platform :ios do
            lane :upload do
              pilot(
                username: "soluservant@gmail.com",
                app_identifier: "co.median.ios.djyjab",
                ipa: "$(pwd)/fastlane/App.ipa",
                skip_waiting_for_build_processing: true
              )
            end
          end
          EOL
          
          # Run fastlane
          fastlane upload
    artifacts:
      - fastlane/App.ipa
secrets:
  - FASTLANE_PASSWORD  # Add this secret in Codemagic for your Apple ID password