# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Paschat testApp"
  lane :upload do
    pilot(
      username: "soluservant@gmail.com",
      app_identifier: "co.median.ios.djyjab",
      ipa: "fastlane/App.ipa",  # Add this line with the correct path
      skip_waiting_for_build_processing: true  # Optional: speeds up the process
    )
  end
end
